name: NetWraith
options:
  bundleIdPrefix: com.netwraith
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "15.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  # ── Main App ──────────────────────────────────────────────
  NetWraith:
    type: application
    platform: iOS
    sources:
      - App
      - Models
      - Views
      - Utilities
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.netwraith.app
        INFOPLIST_FILE: App/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/NetWraith.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: App/NetWraith.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.application-groups:
          - group.com.netwraith.shared
    dependencies:
      - target: PacketTunnelExtension
        embed: true
        codeSign: true
        buildPhase:
          copyFiles:
            destination: plugins

  # ── Packet Tunnel Extension ───────────────────────────────
  PacketTunnelExtension:
    type: app-extension
    platform: iOS
    sources:
      - PacketTunnel
      - Models
      - Utilities
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.netwraith.app.packet-tunnel
        INFOPLIST_FILE: PacketTunnel/Info.plist
        CODE_SIGN_ENTITLEMENTS: PacketTunnel/PacketTunnel.entitlements
    entitlements:
      path: PacketTunnel/PacketTunnel.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.application-groups:
          - group.com.netwraith.shared

schemes:
  NetWraith:
    build:
      targets:
        NetWraith: all
        PacketTunnelExtension: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
